name: AABY
channels:
  - conda-forge
dependencies:
  - python==3.11
  - pyyaml
  - ambertools
  - openbabel
  - parmed
  - propka
  - numpy<1.24
  - pip
  - pip:
      - AABY==0.1.0
      - COBY==1.0.11
